# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 7200s # 2 hours
substitutions:
  _GRAALVM_VERSION: '22.3.2'
steps:
  # GraalVM build
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/graalvm:${_GRAALVM_VERSION}", "--build-arg=GRAALVM_VERSION=$_GRAALVM_VERSION", "."]
    dir: java/graalvm
    id: graalvm-build
    waitFor: ["-"]
  - name: gcr.io/gcp-runtimes/structure_test
    args:
      ["-i", "gcr.io/$PROJECT_ID/graalvm:${_GRAALVM_VERSION}", "--config", ".kokoro/docker/graalvm22.3_jdk11.yaml", "-v"]
    waitFor: ["graalvm-build"]
  - name: gcr.io/cloud-builders/docker
    args:
      [
          "tag",
          "gcr.io/$PROJECT_ID/graalvm:${_GRAALVM_VERSION}",
          "gcr.io/cloud-devrel-public-resources/graalvm:${_GRAALVM_VERSION}",
      ]
    waitFor: ["graalvm-build"]


  # GraalVM JDK 17 build
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/graalvm17:${_GRAALVM_VERSION}", "--build-arg=GRAALVM_VERSION=$_GRAALVM_VERSION", "."]
    dir: java/graalvm17
    id: graalvm17-build
    waitFor: ["-"]
  - name: gcr.io/gcp-runtimes/structure_test
    args:
      ["-i", "gcr.io/$PROJECT_ID/graalvm17:${_GRAALVM_VERSION}", "--config", ".kokoro/docker/graalvm22.3_jdk17.yaml", "-v"]
    waitFor: ["graalvm17-build"]
  - name: gcr.io/cloud-builders/docker
    args:
      [
          "tag",
          "gcr.io/$PROJECT_ID/graalvm17:${_GRAALVM_VERSION}",
          "gcr.io/cloud-devrel-public-resources/graalvm17:${_GRAALVM_VERSION}",
      ]
    waitFor: ["graalvm17-build"]
